-- Migration: add product color variants
-- Generated by Pal 2026-06-14 for feat/color-variants
--
-- Apply order:
--   1. Add OrderItem.color (nullable, no default impact on existing rows)
--   2. Add Product.hasColor (default 0, backfills existing rows automatically)
--   3. Create ProductColor table + indexes
--
-- All changes are additive — no destructive operations, no data loss.
-- Existing products are unaffected (hasColor defaults to false).

BEGIN TRY

BEGIN TRAN;

-- ---------------------------------------------------------------------
-- 1. OrderItem.color
-- ---------------------------------------------------------------------
ALTER TABLE [dbo].[OrderItem] ADD [color] NVARCHAR(1000) NULL;

-- ---------------------------------------------------------------------
-- 2. Product.hasColor
-- ---------------------------------------------------------------------
ALTER TABLE [dbo].[Product] ADD [hasColor] BIT NOT NULL CONSTRAINT [Product_hasColor_df] DEFAULT 0;

-- ---------------------------------------------------------------------
-- 3. ProductColor table
-- ---------------------------------------------------------------------
CREATE TABLE [dbo].[ProductColor] (
    [id]        NVARCHAR(1000) NOT NULL,
    [productId] NVARCHAR(1000) NOT NULL,
    [name]      NVARCHAR(1000) NOT NULL,
    [hex]       NVARCHAR(1000) NOT NULL,
    [sortOrder] INT            NOT NULL CONSTRAINT [ProductColor_sortOrder_df] DEFAULT 0,
    [createdAt] DATETIME2      NOT NULL CONSTRAINT [ProductColor_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2      NOT NULL,
    CONSTRAINT [ProductColor_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [ProductColor_productId_name_key] UNIQUE NONCLUSTERED ([productId], [name])
);

CREATE NONCLUSTERED INDEX [ProductColor_productId_idx]
    ON [dbo].[ProductColor]([productId]);

CREATE NONCLUSTERED INDEX [ProductColor_productId_sortOrder_idx]
    ON [dbo].[ProductColor]([productId], [sortOrder]);

ALTER TABLE [dbo].[ProductColor]
    ADD CONSTRAINT [ProductColor_productId_fkey]
    FOREIGN KEY ([productId]) REFERENCES [dbo].[Product]([id])
    ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
